os:
    - linux
language: node_js
node_js:
    - "8.12.0"
cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle
before_install:
    - npm install -g npm
    - npm install -g yo
    - java -version
    - date
install:
    - npm install
    - npm link
script:
    - npm test
    - cd $HOME
    - git clone https://github.com/jhipster/jhipster-sample-app-ng2
    - cd jhipster-sample-app-ng2
    - npm link generator-jhipster-spring-cloud-stream
    - yo jhipster-spring-cloud-stream default --force
    - ./mvnw clean test
