os:
    - linux
language: node_js
node_js:
    - '10.16.0'
cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle
before_install:
    - npm install -g npm
    - npm install -g yo
install:
    - npm install
    - npm link
script:
    - npm test
    - cd $HOME
    - git clone https://github.com/jhipster/jhipster-sample-app
    - cd jhipster-sample-app
    - npm link generator-jhipster-spring-cloud-stream
    - yo jhipster-spring-cloud-stream default --force
    - ./mvnw clean test
